"""Turn-1 action space encoding for VGC doubles.

Each active mon has 16 action slots: 4 moves × 4 target slots.
Target conventions:
  0 = opponent slot A
  1 = opponent slot B
  2 = ally (other active mon on your side)
  3 = self / no-target (Protect, spread moves, self-buffs)

Tera is a separate 3-way flag (none / tera_A / tera_B) cross-cutting with moves.
Joint action = (mon_A_action, mon_B_action, tera_flag).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np


# ── Move targeting (Showdown-backed) ──────────────────────────────────────

# Raw Showdown target values, keyed by our vocab move names.
# Generated by scripts/gen_move_targets.py from Showdown's moves.json.
_MOVE_TARGETS_PATH = Path(__file__).parent / "move_targets.json"
_MOVE_TARGETS: dict[str, str] = {}
if _MOVE_TARGETS_PATH.exists():
    with open(_MOVE_TARGETS_PATH) as f:
        _MOVE_TARGETS = json.load(f)

# Showdown target value → our mask behavior category
_SHOWDOWN_TO_CATEGORY: dict[str, str] = {
    # Single-target (player chooses target)
    "normal": "single",
    "any": "single",
    "adjacentFoe": "single",
    # Self / no player target choice
    "self": "self",
    "allySide": "self",
    "allyTeam": "self",
    "foeSide": "self",
    "all": "self",
    "scripted": "self",
    "randomNormal": "self",
    "adjacentAllyOrSelf": "self",
    "allies": "self",
    # Ally-only
    "adjacentAlly": "ally",
    # Spread (multi-target)
    "allAdjacentFoes": "spread",
    "allAdjacent": "spread",
}

# Single-target moves where ally-targeting is a real strategic choice.
# Domain knowledge Showdown can't encode — these are "normal" target in
# Showdown but have strategic ally-targeting uses in VGC doubles.
DUAL_PURPOSE_MOVES: set[str] = {
    "Pollen Puff",      # heals ally, damages enemy
    "Beat Up",          # triggers Justified on ally
    "Frost Breath",     # guaranteed crit → triggers Anger Point
    "Skill Swap",       # swap abilities with ally
    "Swagger",          # +2 Atk (Own Tempo / Lum Berry ally)
    "Psych Up",         # copy predicted ally stat boosts
    "Role Play",        # copy ally's ability
    "Worry Seed",       # remove bad ability from ally
    "Gastro Acid",      # suppress ally's bad ability
    "Entrainment",      # give your ability to ally
    "Simple Beam",      # give ally Simple before they boost
}

# Everything else = single-target (can target opponent A, opponent B, or ally)


# ── Per-mon action encoding ──────────────────────────────────────────────

NUM_MOVE_SLOTS = 4
NUM_TARGET_SLOTS = 4
SLOTS_PER_MON = NUM_MOVE_SLOTS * NUM_TARGET_SLOTS  # 16

# Tera flag: 0=none, 1=tera_A, 2=tera_B
TERA_NONE = 0
TERA_A = 1
TERA_B = 2
NUM_TERA = 3


def move_target_to_slot(move_idx: int, target: int) -> int:
    """Convert (move_index, target_slot) → flat action slot (0-15)."""
    assert 0 <= move_idx < NUM_MOVE_SLOTS
    assert 0 <= target < NUM_TARGET_SLOTS
    return move_idx * NUM_TARGET_SLOTS + target


def slot_to_move_target(slot: int) -> tuple[int, int]:
    """Convert flat action slot (0-15) → (move_index, target_slot)."""
    assert 0 <= slot < SLOTS_PER_MON
    return divmod(slot, NUM_TARGET_SLOTS)


def get_target_category(move_name: str) -> str:
    """Classify a move's targeting type using Showdown data.

    Returns one of: 'self', 'ally', 'spread', 'single'.
    """
    if move_name == "UNK":
        return "single"
    raw = _MOVE_TARGETS.get(move_name)
    if raw is None:
        return "single"  # unknown move fallback
    return _SHOWDOWN_TO_CATEGORY.get(raw, "single")


def compute_action_mask(moves: list[str], ally_alive: bool = True,
                        opp_a_alive: bool = True, opp_b_alive: bool = True) -> np.ndarray:
    """Compute a (16,) boolean mask of valid action slots for one active mon.

    Args:
        moves: list of 4 move names (from OTS, canonicalized).
        ally_alive: whether the partner active mon is alive.
        opp_a_alive: whether opponent slot A is alive.
        opp_b_alive: whether opponent slot B is alive.

    Returns:
        (16,) bool array. True = valid slot.
    """
    mask = np.zeros(SLOTS_PER_MON, dtype=bool)

    for move_idx, move_name in enumerate(moves):
        if move_name == "UNK":
            continue  # can't use unknown moves

        cat = get_target_category(move_name)

        if cat == "self" or cat == "spread":
            # Only target 3 valid
            mask[move_target_to_slot(move_idx, 3)] = True
        elif cat == "ally":
            # Only target 2 valid (if ally alive)
            if ally_alive:
                mask[move_target_to_slot(move_idx, 2)] = True
        else:
            # Single-target: can hit opponent A, opponent B, ally, or self
            # Target 2 (ally) is legal in VGC (e.g., Weakness Policy activation)
            # Target 3 (self) handles protocol quirks where failed/redirected
            # moves show the user targeting their own slot
            if opp_a_alive:
                mask[move_target_to_slot(move_idx, 0)] = True
            if opp_b_alive:
                mask[move_target_to_slot(move_idx, 1)] = True
            if ally_alive:
                mask[move_target_to_slot(move_idx, 2)] = True
            mask[move_target_to_slot(move_idx, 3)] = True

    return mask


def compute_strategic_mask(moves: list[str], ally_alive: bool = True,
                           opp_a_alive: bool = True, opp_b_alive: bool = True) -> np.ndarray:
    """Compute a (16,) boolean mask of *strategically choosable* action slots.

    Identical to compute_action_mask except that single-target moves do NOT
    include target=3 (self).  Target=3 for single-target moves exists in the
    replay data only as a protocol artifact (failed / redirected moves); a
    player cannot intentionally choose to target themselves with Thunderbolt.

    Self-target and spread moves still use target=3 (that IS the correct
    strategic choice).

    Use this mask for payoff enumeration / Nash solving.
    Use compute_action_mask for BC training (matching replay data).
    """
    mask = np.zeros(SLOTS_PER_MON, dtype=bool)

    for move_idx, move_name in enumerate(moves):
        if move_name == "UNK":
            continue

        cat = get_target_category(move_name)

        if cat == "self" or cat == "spread":
            mask[move_target_to_slot(move_idx, 3)] = True
        elif cat == "ally":
            if ally_alive:
                mask[move_target_to_slot(move_idx, 2)] = True
        else:
            # Single-target: opponents always valid
            # NO target=3 (self) — not a strategic choice
            # Ally targeting only for dual-purpose moves (Pollen Puff etc.)
            if opp_a_alive:
                mask[move_target_to_slot(move_idx, 0)] = True
            if opp_b_alive:
                mask[move_target_to_slot(move_idx, 1)] = True
            if ally_alive and move_name in DUAL_PURPOSE_MOVES:
                mask[move_target_to_slot(move_idx, 2)] = True

    return mask


# ── Joint action encoding ────────────────────────────────────────────────

@dataclass
class Turn1Action:
    """A single mon's turn-1 action: which move, which target."""
    move_idx: int     # 0-3 (index in OTS moveset)
    target: int       # 0-3 (target slot)
    slot: int         # 0-15 (flat encoding)

    def to_dict(self) -> dict[str, int]:
        return {"move_idx": self.move_idx, "target": self.target, "slot": self.slot}

    @classmethod
    def from_dict(cls, d: dict[str, int]) -> Turn1Action:
        return cls(**d)

    @classmethod
    def from_slot(cls, slot: int) -> Turn1Action:
        move_idx, target = slot_to_move_target(slot)
        return cls(move_idx=move_idx, target=target, slot=slot)

    @classmethod
    def from_move_target(cls, move_idx: int, target: int) -> Turn1Action:
        return cls(move_idx=move_idx, target=target,
                   slot=move_target_to_slot(move_idx, target))


@dataclass
class JointAction:
    """Joint action for one side: both active mons + tera flag."""
    action_a: Turn1Action | None  # None if mon fainted before acting
    action_b: Turn1Action | None
    tera_flag: int  # 0=none, 1=tera_A, 2=tera_B

    def to_dict(self) -> dict[str, Any]:
        return {
            "action_a": self.action_a.to_dict() if self.action_a else None,
            "action_b": self.action_b.to_dict() if self.action_b else None,
            "tera_flag": self.tera_flag,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> JointAction:
        return cls(
            action_a=Turn1Action.from_dict(d["action_a"]) if d["action_a"] else None,
            action_b=Turn1Action.from_dict(d["action_b"]) if d["action_b"] else None,
            tera_flag=d["tera_flag"],
        )
